In [1]:
import numpy as np

# Array concatenation
here we have separate RGB channels of an image, concatenate them using `np.concatenate` and `np.stack` separately

In [2]:
h, w = 224, 224
R = np.random.randint(0, 256, size=(h, w))
G = np.random.randint(0, 256, size=(h, w))
B = np.random.randint(0, 256, size=(h, w))

In [3]:
# your code here #
img1 = np.concatenate(
        [R[None, ...],
         G[None, ...],
         B[None, ...]], axis=0)
assert img1.shape == (3, h, w)

img2 = np.stack([R, G, B], axis=0)
assert img2.shape == (3, h, w)

# Array creation
`p` is a 1D array indicating probability of being dog(y=1). let's say all samples are truly dog and we need to create a ground-truth array for loss computation (don't worry :) you don't need to implement loss function here). imagine you can't explicitly use any shape information for this matter.

In [4]:
num_samples = 100
p = np.random.rand(num_samples)

In [5]:
# your code here
y_gt = np.ones_like(p)

# Data stats
`salary` is a 2D array denoting salaries of six employees during 100 months. let's say the manager asks you to analyze his/her employees by answering the following questions (`np.argmax`, `np.max`, `np.argwhere`, `np.median` and `np.percentile` could be helpful :) )

In [6]:
salary = np.random.randint(5, 150, size=(6, 100))

1. for 2nd employee, most salary earned during a month and when

In [7]:
# your code here
print(salary[2].argmax(), salary[2].max())

98 148


2. find most salary earned, by whom and when (might be multiple employees in multiple times)

In [8]:
# your code here
print(salary.max())
np.argwhere(salary == salary.max())

149


array([[ 1, 43],
       [ 1, 98],
       [ 3, 16],
       [ 5, 56],
       [ 5, 62]])

3. per employee, the median salary they earned

In [9]:
# your code here
np.median(salary, 1)

array([ 81.5,  83.5,  85.5,  84. ,  80. , 106. ])

4. per employee, their 25th max salary they earned

In [10]:
# your code here
np.percentile(salary, 75, axis=1)

array([110.  , 114.  , 113.5 , 114.  , 119.25, 127.  ])

# Indexing and slicing
`salary` is salaries of six employees during a year. implement code for the following parts

In [11]:
salary = np.random.randint(5, 100, size=(6, 12))

1. show the salary of all employees in second month

In [12]:
# your code here
salary[:, 1]

array([17, 66, 92,  9, 26, 81])

2. show the salary of 1st and 3rd employees in even months

In [13]:
# your code here
salary[[1, 3], ::2]

array([[27, 91, 29,  9, 25, 95],
       [82, 27, 29, 87, 21, 84]])

3. show salary of 1st employee in 5th month, 2nd one in 11st, 3rd in 7th

In [14]:
# your code here
salary[np.arange(1, 4), [4, 11, 7]]

array([29, 41,  9])

# Other utilities

1. create an array of 1000 samples in a linear form between 0 and 1 using `np.linspace` and check the difference of all two subsequent elements are close to 0.001

In [20]:
# your code here
arr = np.linspace(0, 1, 1000)
assert np.allclose(np.diff(arr), 0.001, atol=1e-4)

2. increase value of `arr` by one in places provided by `indices`

In [16]:
arr = np.zeros(5)
indices = np.random.randint(0, 5, size=(1000))

In [17]:
# your code here
np.add.at(arr, indices, 1)
assert np.sum(arr) == 1000

3. for `arr`, select the 4th and 5th axis of last dimension using both numpy indexing and ellipsis and check their value equality using `np.all`

In [18]:
arr = np.random.rand(10, 10, 10, 10, 10, 8)

In [19]:
# your code here
res1 = arr[..., [4, 5]]
res2 = arr[:, :, :, :, :, [4, 5]]
assert np.all(res1 == res2)